#!/bin/sh
set -e

dpkg-source --before-build `pwd`
dpkg-buildpackage -rfakeroot --target=pre-build
dpkg-buildpackage -rfakeroot --target=common-configure-arch 2>/dev/null
make -C src/base libbase.la
make -C src globals.o
make -C lib all
make -C compat
make -C src squid.conf.default
make -C test-suite check
