#!/bin/sh
set -e

dpkg-source --before-build `pwd`
dh_update_autotools_config
dh_autoreconf
dh_auto_configure -- ${DEB_CONFIGURE_EXTRA_FLAGS} --with-gnutls
make -C src/base libbase.la
make -C src/mem libmem.la
make -C src globals.o
make -C lib all
make -C compat
make -C src squid.conf.default
make -C test-suite check
