#! /bin/sh

set -e


case "$1" in
	configure)
		#
		# Fix directory->link transition for /usr/share/squid3/errors in
		# 3.0.STABLE15-1: all has gone well, remove temporary directory
		#
		if [ -d "/usr/share/squid3/errors.pre_link_transition" ]
		then
			rm -rf /usr/share/squid3/errors.pre_link_transition
		fi

		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		;;
	*)
		#
		#	Unknown action - do nothing.
		#
		exit 0
		;;
esac

