etc/squid3/squid.conf
etc/squid3/squid.conf.documented /usr/share/doc/squid3
etc/squid3/msntauth.conf
etc/squid3/errorpage.css
etc/logrotate.d
etc/resolvconf.d
etc/init.d/squid3
usr/lib/squid3
usr/sbin/squid3
usr/share/man/man8/squid3.8
usr/share/man/man8/squid3_pam_auth.8
usr/share/man/man8/squid3_ldap_auth.8
usr/share/man/man8/squid3_ldap_group.8
usr/share/man/man8/squid3_session.8
usr/share/man/man8/squid3_unix_group.8
